### PR TITLE
Handle spaces in configFile and source file paths

### LINKED ISSUE #7: Spaces in source file paths cause danger-swiftlint to fail
Attached is a screenshot of the output from a PR that changed a file with a space in the path.

screen shot 2018-02-14 at 7 49 16 pm

### PR DESCRIPTION
**Pull request by Killectro**
This should fix #7.

Let me know if there is anything I need to do in terms of more tests, etc. or anything that I missed! Thanks for the plugin btw, it's going to be a huge help moving forward for us.

### CODE REVIEW

**Comment by Killectro** [comment]
I see the CHANGELOG message now but I'm not sure what version and such so if you give me a little guidance there I can do that as well 👍

**Comment by sunshinejr** [comment]
Hey @Killectro, this looks really solid, thank you for catching these! 💯 

About the Changelog, just add a line under `Next` header and remove this `Nothing yet!` text ([see this for reference](https://github.com/ashfurrow/danger-swiftlint/pull/5/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)).

**Comment by Killectro** [comment]
Updated 👍

**Review by ashfurrow — APPROVED** [review]
Well done, thank you for including test coverage 👍 I'll merge and release this.

**Comment by Killectro** [comment]
<3 Thanks Ash and Łukasz!

**Pull request merged**
