### PR TITLE
Introduce `binary_path` option

### LINKED ISSUE #44: Add feature to set SwiftLint execution path
I integrate SwiftLint via CocoaPods, so `swiftlint` execution path is different than usual.

I want new feature to set SwiftLint path.

https://github.com/ashfurrow/danger-swiftlint/blob/master/ext/swiftlint/swiftlint.rb#L55

### PR DESCRIPTION
**Pull request by giginet**
closes #44 

# Motivation

I want to set execution path of SwiftLint

# Usage

If you installs SwiftLint via CocoaPods, you can use like following:

```ruby
swiftlint.binary_path = "./Pods/SwiftLint/swiftlint"
```

### CODE REVIEW

**Comment by giginet** [comment]
Thanks!

**Comment by ashfurrow** [comment]
Cool, thanks for the PR! I'll get this deployed to RubyGems.

**Comment by ashfurrow** [comment]
Cool cool, all done. You should be good to upgrade to 0.6.0 now 👍 Anyone available for a PR that adds this option to the README?

**Comment by marcelofabri** [comment]
> Anyone available for a PR that adds this option to the README?

This PR actually already did that (see df85fbd)

**Comment by ashfurrow** [comment]
Ha, perfect!

**Pull request merged**
