### PR TITLE
Add escaping for 'directory' variable

### PR DESCRIPTION
**Pull request by Austinate**
This PR fixes issue described in #62 
Thanks for fast response, @ashfurrow 😊

### CODE REVIEW

**Comment by victorg1991** [comment]
Hey this looks amazing! 🎉 What do you think abouy adding a new test case that check this? 😄

**Comment by Austinate** [comment]
@victorg1991 Hi, Thanks!
I've added a test, it's my first experience with Rake so please advice if something is wrong :)

**Comment by Austinate** [comment]
thanks a lot for help with PR and and such a nice tool again! 😌

**Comment by ashfurrow** [comment]
Thanks again – this has been pushed as version 0.10.2.

**Pull request merged**
